Undistort 2D points function
kornia/kornia pull request #1026
Opened 2021-05-23 01:47 UTC by jhacsonmeza

### Description
`undistort_points` function to compensate for lens distortion a set of 2D points. Radial, tangential, thin prism, and tilt distortion are considered. Additionally `inverseTiltProjection` function is used for the tilt distortion compensation.

2021-05-24 14:54 UTC, edgarriba commented
@jhacsonmeza could you add some uni tests? Check the ones e.g. in geometry epipolar

2021-05-27 00:20 UTC, jhacsonmeza commented
I've added a unit test `test_opencv` where I used two distortion coefficients to be compared with the results given by OpenCV.

2021-06-05 09:53 UTC, edgarriba commented
@jhacsonmeza @dkoguciuk as for the format we don’t have to worry that much any more since we have not the pre-commit bot (update your pr with master for that). As for gradcheck, make sure that any operations doesn’t contain possible zero divisions. Besides, I’d suggest as discussed in slack to provide batched functionality to make easier to compute e.g loss functions

2021-06-08 01:46 UTC, jhacsonmeza commented
@dkoguciuk thank you. I'm going to modify the code to be aligned with pep8. I've used pytest to check my unit test, and I'm working in a problem.

2021-06-08 21:00 UTC, edgarriba commented
@jhacsonmeza code format shouldn’t be a problem any more since the precommit-ci will fix fir you every time you push a commit to the branch

2021-06-11 07:55 UTC, edgarriba requested changes

2021-06-11 07:55 UTC, edgarriba commented on test/geometry/calibration/test_undistort.py
> +            [[1028.0374, 788.7520], [1025.1218, 716.8726], [1022.1792, 645.1857]], device=device, dtype=dtype
```suggestion
            [[[1028.0374, 788.7520], [1025.1218, 716.8726], [1022.1792, 645.1857]]], device=device, dtype=dtype
```

2021-06-11 07:55 UTC, edgarriba commented on test/geometry/calibration/test_undistort.py
> +            [[1030.5992, 790.65533], [1027.3059, 718.10020], [1024.0700, 645.90600]], device=device, dtype=dtype
```suggestion
            [[[1030.5992, 790.65533], [1027.3059, 718.10020], [1024.0700, 645.90600]]], device=device, dtype=dtype
```

2021-06-11 07:55 UTC, edgarriba commented on test/geometry/calibration/test_undistort.py
> +        # ----- Test 1: using 5 distortion coefficients
Also Split in three different tests
test_opencv_five_coeff
test_opencv_all_coeff
test_opencv_stereo

2021-06-11 09:12 UTC, edgarriba approved these changes

2021-06-11 09:35 UTC, lferraz approved these changes

2021-06-11 12:34 UTC, edgarriba commented on kornia/geometry/calibration/undistort.py
> +        pointsUntilt = torch.stack([x, y, torch.ones(x.shape, dtype=x.dtype)], -1) @ invTilt.transpose(-2, -1)
```suggestion
        pointsUntilt = torch.stack([x, y, torch.ones(x.shape, device=x.device, dtype=x.dtype)], -1) @ invTilt.transpose(-2, -1)
```

2021-06-11 13:28 UTC, merged