release 0.5.3
kornia/kornia pull request #1036
Opened 2021-05-29 10:44 UTC by edgarriba

### Description
A few sentences describing the changes proposed in this pull request.

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

## PR Checklist
### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our 
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [ ] **Pass all tests**: did you test in local ? `make test`
- [ ] Unittests: did you add tests for your new functionality ?
- [ ] Documentations: did you build documentation ? `make build-docs`
- [ ] Implementation: is your code well commented and follow conventions ? `make lint`
- [ ] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>
  
  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if 
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?
 
</details>

2021-05-29 11:07 UTC, ducha-aiki requested changes

2021-05-29 11:07 UTC, ducha-aiki commented on CHANGELOG.md
> +- Refactorization of the morphology package ([#1034](https://github.com/kornia/kornia/pull/1034))
Add that it is a breaking change, as the function behaviour is changed - before it was not correct

2021-05-29 11:07 UTC, ducha-aiki commented on CHANGELOG.md
> +- Refactorization of the morphology package ([#1034](https://github.com/kornia/kornia/pull/1034))
Morphology, I mean

2021-05-29 16:39 UTC, Borda commented
I do not think that the release workflow is worse to mention in changelog =)

2021-05-30 07:36 UTC, edgarriba commented on CHANGELOG.md
> +- Refactorization of the morphology package ([#1034](https://github.com/kornia/kornia/pull/1034))
in theory breaking changes are included in this category. We are following this convention: https://keepachangelog.com/en/1.0.0/

2021-05-30 08:01 UTC, merged