[feat] Added differentiable HD loss
kornia/kornia pull request #1254
Opened 2021-09-03 18:10 UTC by shijianjian

### Description
Added differentiable erosion-based HD loss.

2021-09-05 11:59 UTC, edgarriba requested changes
LGTM - add tests, attach to docs and update changelog

2021-09-05 11:59 UTC, edgarriba commented on kornia/losses/hausdorff.py
> +        alpha: controls the erosion rate in each iteration. Default: 2.0.
```suggestion
        alpha: controls the erosion rate in each iteration.
```

2021-09-05 11:59 UTC, edgarriba commented on kornia/losses/hausdorff.py
> +        erosions: the number of iterations of erosion. Default: 10.
```suggestion
        erosions: the number of iterations of erosion.
```

2021-09-05 11:59 UTC, edgarriba commented on kornia/losses/hausdorff.py
> +    def get_kernel(self) -> None:
```suggestion
    def get_kernel(self) -> torch.Tensor:
```

2021-09-05 11:59 UTC, edgarriba commented on kornia/losses/hausdorff.py
> +            eroted = eroted + erosion * (k + 1) ** self.alpha
```suggestion
            eroded = eroded + erosion * (k + 1) ** self.alpha
```

2021-09-05 11:59 UTC, edgarriba commented on kornia/losses/hausdorff.py
> +        return eroted
```suggestion
        return eroded
```

2021-09-05 11:59 UTC, edgarriba commented on kornia/losses/hausdorff.py
> +        assert pred.shape[2:] == target.shape[2:] and pred.size(0) == target.size(0) and target.size(1) == 1, (
add if / raise - same for the other assertion
https://deepsource.io/gh/kornia/kornia/run/f0e4fe5a-a07d-407b-a7c4-6e7b40f37f37/python/BAN-B101

2021-09-05 11:59 UTC, edgarriba commented on kornia/losses/hausdorff.py
> +            target: target tensor with a shape of :math:`(B, 1, H, W)`.
add the return description

2021-09-05 11:59 UTC, edgarriba commented on kornia/losses/hausdorff.py
> +        alpha: controls the erosion rate in each iteration. Default: 2.0.
```suggestion
        alpha: controls the erosion rate in each iteration.
```

2021-09-05 11:59 UTC, edgarriba commented on kornia/losses/hausdorff.py
> +        erosions: the number of iterations of erosion. Default: 10.
```suggestion
        erosions: the number of iterations of erosion.
```

2021-09-05 11:59 UTC, edgarriba commented on kornia/losses/hausdorff.py
> +    def get_kernel(self) -> None:
```suggestion
    def get_kernel(self) -> torch.Tensor:
```

2021-09-05 11:59 UTC, edgarriba commented on kornia/losses/hausdorff.py
> +            target: target tensor with a shape of :math:`(B, 1, D, H, W)`.
add the return description

2021-09-12 17:40 UTC, shijianjian commented
> Is there any paper reference that we can add here ?

It has been there in the first place.

2021-09-12 18:23 UTC, shijianjian commented
@ducha-aiki There are [smoke test errors](https://github.com/kornia/kornia/pull/1254/checks?check_run_id=3580607078) in LoFTR, can you take a look?

2021-09-13 08:57 UTC, edgarriba approved these changes
LGTM. Are you aware of any potential example that we could show for this functionality ?

2021-09-13 14:10 UTC, shijianjian commented
> LGTM. Are you aware of any potential example that we could show for this functionality ?

This is used to improve semantic segmentation performances, similar to dice loss. Probably worth adding some illustrations to the docs.

2021-09-13 15:39 UTC, merged