add exception test for se2 + small bug fix
kornia/kornia pull request #2160
Opened 2023-01-19 17:53 UTC by cjpurackal

#### Changes

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

2023-01-19 18:01 UTC, johnnv1 requested changes
Just a small fix for the tests 😄

2023-01-19 18:10 UTC, edgarriba approved these changes

2023-01-20 16:45 UTC, cjpurackal commented on test/geometry/liegroup/test_se2.py
> +            assert Se2(r, t2)
got it :thumbsup:

2023-01-20 17:00 UTC, johnnv1 commented on test/geometry/liegroup/test_se2.py
> +            assert Se2(r, t2)
Can you split this case with other `with pytest.raises(ValueError):` context, and fix the other's exception cases?

2023-01-23 17:20 UTC, johnnv1 approved these changes

2023-01-24 19:23 UTC, merged