Make use of composition for augmentation multiprocessing friendliness
kornia/kornia pull request #2552
Opened 2023-09-20 15:07 UTC by NielsPichon

#### Changes

Modifies the UniformDistributed augmentation such that it uses composition. This would ultimately allow to make any other transform multiprocessing easy. 

Design note: I initially wanted to override `__setattr__` but then came back on my decision as this could result in unwanted copies during operations beyond  the initialization. Instead I simply clone input tensors upon initialization.

Addresses [this comment](https://github.com/kornia/kornia/pull/2499#discussion_r1308401158) from @edgarriba in my previous PR

#### Type of change

Small Refactor

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

2023-09-21 12:25 UTC, edgarriba reviewed
@NielsPichon can you rebase with master. We fixed some stuff to solve ci issues

2023-09-21 12:49 UTC, NielsPichon commented
> @NielsPichon can you rebase with master. We fixed some stuff to solve ci issues

Done 👍

2023-09-21 16:19 UTC, edgarriba requested changes
seems typing is failing. The other idk

2023-09-22 10:23 UTC, edgarriba approved these changes
LGTM from code qa side

2023-09-22 11:23 UTC, NielsPichon commented
> seems typing is failing. The other idk

It looks tome that the test is flagging the lack of typing or *args and **kwargs which do not require any typing. I guess I could type them as Tuple[Any] and Dict[str, Any] but this goes against python typing recommandations... Any suggestion?

2023-09-23 06:41 UTC, edgarriba reviewed
I don’t see any other option here other that the typing you suggested

2023-09-25 21:25 UTC, johnnv1 commented on kornia/augmentation/_multiprocessing.py
> +    def __init__(self, *args, **kwargs) -> None:
just add Any here or # type: ignore

2023-10-15 11:44 UTC, edgarriba commented
@NielsPichon typing seems to be wrong

2023-10-28 13:23 UTC, johnnv1 commented
closing in favor of https://github.com/kornia/kornia/pull/2637

2023-10-28 13:23 UTC, closed without merging