Introduce Tikhonov Regularization to get_tps_transform
kornia/kornia pull request #2690
Opened 2023-12-17 22:43 UTC by fschiffers

During testing, I observed that the TPS transformation could produce erratic warping effects when dealing with misaligned control points ( e.g. a translation and a scale).

To address this, we've added an optional Tikhonov regularization parameter (lambda_reg) to the get_tps_transform function. This regularization significantly improves the stability and smoothness of the warp.

- Introduced lambda_reg for optional regularization to improve warp smoothness
- Expanded documentation with practical insights on regularization benefits
- Maintained backward compatibility with lambda_reg defaulting to None

2023-12-18 10:13 UTC, edgarriba requested changes
is there any test that we can add to validate this and can reflect the issue mentioned?

2023-12-18 10:13 UTC, edgarriba commented on kornia/geometry/transform/thin_plate_spline.py
> +        identity_matrix = torch.eye(num_points, device=device, dtype=dtype).unsqueeze(0).repeat(batch_size, 1, 1)
```suggestion
        identity_matrix = eye_like(num_points)
```
`from kornia.utils import eye_like`

2023-12-18 10:13 UTC, edgarriba commented on kornia/geometry/transform/thin_plate_spline.py
> +    zero_mat: torch.Tensor = torch.zeros(batch_size, 3, 3, device=device, dtype=dtype)
```suggestion
    zero_mat: torch.Tensor = zeros(batch_size, 3, 3, device=device, dtype=dtype)
```
use as much as possible from kornia.core

2023-12-18 10:13 UTC, edgarriba commented on kornia/geometry/transform/thin_plate_spline.py
> +    l_matrix = torch.cat((k_matrix, p_matrix), -1)
```suggestion
    l_matrix = concatenate((k_matrix, p_matrix), -1)
```
from core too

2023-12-18 21:57 UTC, fschiffers commented
you can the following code (assuming you have the lambda_reg option in your code). It should provide you with the attached images. The lower 2 ones show the warping of a grid of points onto the desired output space.

With regularization the warping is somewhat correct, without regularization, some weird stuff happens. 

Please let me know if you need any further tests.

```

import kornia
import torch
import matplotlib.pyplot as plt

points_input = torch.Tensor([
        [-1.0000,  1.0040],
        [-0.4992,  1.0040],
        [ 0.0017,  1.0040],
        [ 0.5025,  1.0040],
        [ 1.0033,  1.0040],
        [-1.0000,  0.5030],
        [-0.4992,  0.5030],
        [ 0.0017,  0.5030],
        [ 0.5025,  0.5030],
        [ 1.0033,  0.5030],
        [-1.0000,  0.0020],
        [-0.4992,  0.0020],
        [ 0.0017,  0.0020],
        [ 0.5025,  0.0020],
        [ 1.0033,  0.0020],
        [-1.0000, -0.4990],
        [-0.4992, -0.4990],
        [ 0.0017, -0.4990],
        [ 0.5025, -0.4990],
        [ 1.0033, -0.4990],
        [-1.0000, -1.0000],
        [-0.4992, -1.0000],
        [ 0.0017, -1.0000],
        [ 0.5025, -1.0000],
        [ 1.0033, -1.0000]])[None]

points_output = torch.tensor([
        [-0.2298,  0.5903],
        [-0.0216,  0.6130],
        [ 0.2093,  0.6207],
        [ 0.4402,  0.6130],
        [ 0.6485,  0.5903],
        [-0.2525,  0.3821],
        [-0.0331,  0.3936],
        [ 0.2093,  0.3975],
        [ 0.4518,  0.3936],
        [ 0.6712,  0.3821],
        [-0.2601,  0.1512],
        [-0.0370,  0.1512],
        [ 0.2093,  0.1512],
        [ 0.4556,  0.1512],
        [ 0.6788,  0.1512],
        [-0.2525, -0.0798],
        [-0.0331, -0.0913],
        [ 0.2093, -0.0952],
        [ 0.4518, -0.0913],
        [ 0.6712, -0.0798],
        [-0.2298, -0.2880],
        [-0.0216, -0.3107],
        [ 0.2093, -0.3184],
        [ 0.4402, -0.3107],
        [ 0.6485, -0.2880]])[None]

plt.figure(figsize=(12, 4))
plt.subplot(121)
plt.scatter(points_input[0,:, 0].detach().cpu().numpy(), points_input[0,:, 1].detach().cpu().numpy(), color='blue')
plt.xlim([-1.2, 1.2])
plt.ylim([-1.2, 1.2])
plt.title("Input Points")
plt.subplot(122)
plt.scatter(points_output[0,:, 0].detach().cpu().numpy(), points_output[0,:, 1].detach().cpu().numpy(), color='red')
plt.xlim([-1.2, 1.2])
plt.ylim([-1.2, 1.2])
plt.title("Output Points")
plt.show()

# Create a grid of points. Adjust the grid size as needed
grid_size = 14

x_min = points_output[0,:,0].min()
x_max = points_output[0,:,0].max()

y_min = points_output[0,:,1].min()
y_max = points_output[0,:,1].max()

x_min = -1
x_max = 1

y_min = -1
y_max = 1

x = torch.linspace(x_min, x_max, grid_size)
y = torch.linspace(y_min, y_max, grid_size)

grid_X, grid_Y = torch.meshgrid(x,y)

grid_points = torch.stack([grid_X.flatten(), grid_Y.flatten()], dim=-1).unsqueeze(0)

import matplotlib.pyplot as plt
import kornia

def plot_tps_transform(points_input, point_output, grid_points, lambda_reg=None):
    # Compute TPS transform with or without regularization
    kernel_weights, affine_weights = kornia.geometry.transform.thin_plate_spline.get_tps_transform(
        points_dst = point_output,
        points_src = points_input,
        lambda_reg = lambda_reg
    )

    # Apply the TPS transform to the grid points
    transformed_grid_points = kornia.geometry.transform.thin_plate_spline.warp_points_tps(
        points_src     = grid_points,
        kernel_centers = point_output,
        kernel_weights = kernel_weights,
        affine_weights = affine_weights
    )

    # Plotting
    plt.figure(figsize=(12, 4))

    # Plot input points
    plt.subplot(121)
    plt.scatter(grid_points[0, :, 0].detach().cpu().numpy(), grid_points[0, :, 1].detach().cpu().numpy(), color='blue')
    plt.xlim([-1, 1])
    plt.ylim([-1, 1])
    plt.title("Input Points")

    # Plot output points
    plt.subplot(122)
    plt.scatter(transformed_grid_points[0, :, 0].detach().cpu().numpy(), transformed_grid_points[0, :, 1].detach().cpu().numpy(), color='red')
    plt.title("Output Points")
    plt.xlim([-1, 1])
    plt.ylim([-1, 1])
    
    plt.show()

plot_tps_transform(
    points_input  =   points_input,
    point_output  =   points_output,
    grid_points =   grid_points,
    lambda_reg  =   0
    )

plot_tps_transform(
    points_input  =   points_input,
    point_output  =   points_output,
    grid_points =   grid_points,
    lambda_reg  =   1
    )
```

![image](https://github.com/kornia/kornia/assets/13521689/af2f16e9-d0f1-4d4c-814c-467197ed5929)
![image](https://github.com/kornia/kornia/assets/13521689/38804bdc-f680-4021-9bf7-bec64feed6dd)
![image](https://github.com/kornia/kornia/assets/13521689/b3d3e1b6-c6c5-431d-b204-8f70e35cf078)

Here's an example of the use case that I'm using (with real images, code not included)
Without Regularization:

( You can see a pretty catastrophic warping failure here)

![image](https://github.com/kornia/kornia/assets/13521689/0ae599cf-0c5c-4101-a23d-d822404e95ba)
![image](https://github.com/kornia/kornia/assets/13521689/0d575d68-64ca-40a8-a34b-1c9dbaa85f9e)

With Regularization:

![image](https://github.com/kornia/kornia/assets/13521689/14dc19d6-8a0a-461c-82ca-a036e264b29f)
![image](https://github.com/kornia/kornia/assets/13521689/51f25856-d27b-4ad3-ad7c-3eb1fb91fb31)

2023-12-19 10:03 UTC, edgarriba commented
awesome -- for tests we could add that to expand this: https://github.com/kornia/kornia/blob/master/test/geometry/transform/test_thin_plate_spline.py

the visual results i think they would be very valuable once we merge this feature that can be added as a notebook tutorial showing TPS usage with kornia?  See: https://github.com/kornia/tutorials  /cc @johnnv1 can guide you to include there

2023-12-19 10:04 UTC, edgarriba commented on kornia/geometry/transform/thin_plate_spline.py
> -from kornia.core import ones, zeros
don't remove this

2023-12-19 10:04 UTC, edgarriba commented on kornia/geometry/transform/thin_plate_spline.py
> -from kornia.core import ones, zeros
https://github.com/kornia/kornia/actions/runs/7251009034/job/19752466964?pr=2690

2024-02-07 00:50 UTC, fschiffers commented
I currently don't have the time for it. Sorry!

2024-03-14 21:54 UTC, closed without merging

2024-03-14 22:17 UTC, johnnv1 commented
as part of https://github.com/kornia/kornia/discussions/2719 plan, we have deleted the `master` in favor of `main`, if anyone has an interest in keep/restart working on this, let me know to help you.