fix: same_on_batch behavior in _adapted_rsampling for shapes of size 1
kornia/kornia pull request #2699
Opened 2023-12-26 13:01 UTC by fortminors

#### Changes

`torch.repeat` is called on the final rsampled tensor, repeating only the batch dimension and just copying the rest

Fixes # (issue)
https://github.com/kornia/kornia/issues/2698

#### Type of change

- [ ] 🧪 Tests Cases
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

2023-12-27 11:12 UTC, edgarriba requested changes
Can you expand the test set to identify this issue ?

2023-12-27 12:30 UTC, fortminors commented
@edgarriba Done. Please, take a look at the test case

2023-12-28 10:06 UTC, edgarriba approved these changes

2023-12-28 10:06 UTC, edgarriba commented on test/augmentation/test_augmentation.py
> +        center_x = torch.tensor([-0.3, 0.3])
```suggestion
        center_x = torch.tensor([-0.3, 0.3], device=device, dtype=dtype)
```

2023-12-28 10:06 UTC, edgarriba commented on test/augmentation/test_augmentation.py
> +        center_y = torch.tensor([-0.3, 0.3])
```suggestion
        center_y = torch.tensor([-0.3, 0.3], device=device, dtype=dtype)
```

2023-12-28 10:38 UTC, merged