WIP: Add DeDoDe detector+descriptor
kornia/kornia pull request #2787
Opened 2024-02-07 17:09 UTC by Parskatt

#### Changes

Adds dedode: https://github.com/parskatt/dedode 

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

2024-02-07 17:12 UTC, Parskatt commented
@ducha-aiki made some start at adding dedode, let me know issues. I'll fix the obvious linter errors and so on.

2024-02-08 09:21 UTC, ducha-aiki commented
Looks good overall. Could you please add a normalization function to the models, so the input image will be in [0,1] range, and you do the ImageNet normalization internally?

2024-02-08 10:08 UTC, edgarriba requested changes
Thanks for the PR ! i left a bunch of comments specially because we are adding a large codebase here and potential things to be abstracted later to reuse existing pieces inside kornia. I leave the final review to @johnnv1

2024-02-08 10:11 UTC, Parskatt commented on kornia/feature/dedode/decoder.py
> +        with torch.autocast("cuda", enabled=self.amp, dtype=self.amp_dtype):
I had issues that autocasting to float16 doesnt work for cpu, which I think it defaults to now, need to check.

2024-02-08 10:14 UTC, Parskatt commented on kornia/feature/dedode/dedode.py
> +                descriptions.float(), keypoints[:, None], mode="bilinear", align_corners=False
This could have issues if images are in float16, I want specifically float32 here

2024-02-08 10:15 UTC, Parskatt commented on kornia/feature/dedode/detector.py
> +            logits = logits + delta_logits.float()  # ensure float (need bf16 doesnt have f.interpolate)
Want specifically float32

2024-02-08 10:19 UTC, Parskatt commented on test/feature/test_dedode.py
> +        dedode = DeDoDe(descriptor_model="G").to(device, dtype)
Sounds good.

2024-02-08 10:48 UTC, ducha-aiki commented on kornia/feature/dedode/decoder.py
> +        amp_dtype=torch.float16,
I believe that it is better to have a fix and at leaset theoretical ability to run anywhere, at least for debug purposes. I love my macbook :)

2024-02-08 10:48 UTC, ducha-aiki commented on kornia/feature/dedode/transformer/layers/mlp.py
@edgarriba Yes, but only if that doen't affect the model itself.

2024-02-08 10:50 UTC, ducha-aiki commented on test/feature/test_dedode.py
> +        dedode = DeDoDe(descriptor_model="G").to(device, dtype)
You can use DISK tests as an example - run on some small images with low amount of keypoints.
https://github.com/kornia/kornia/blob/2a56ccd1fde734848cd94b38d06d14ef6e765e6a/tests/feature/test_disk.py#L43

2024-02-08 10:55 UTC, ducha-aiki commented on kornia/feature/dedode/dedode.py
> +                descriptions.float(), keypoints[:, None], mode="bilinear", align_corners=False
@edgarriba no, we can do a workaround

2024-03-13 07:39 UTC, ducha-aiki commented
Closing in favor of https://github.com/kornia/kornia/pull/2835

2024-03-13 07:39 UTC, closed without merging