Fix: `RandomJPEG` bug with different devices
kornia/kornia pull request #2883
Opened 2024-04-13 17:03 UTC by ditwoo

#### Changes

Fixes # (issue)

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [+] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [+] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

2024-04-14 19:56 UTC, johnnv1 requested changes
even though it fixes your issue, this shouldn't be necessary...

The real issue is in the random generator https://github.com/kornia/kornia/blob/2387a2d165a977f1646332d6cbe6b915a4806e37/kornia/augmentation/random_generator/_2d/jpeg.py#L53 which is allocating and then casting it to the wrong device 

Can you test if in this case, where you want to use the nontensor as the bounds inputs, if you use the 

```python
import torch
from kornia.augmentation import RandomJPEG

device = "cuda"
jpegq = (1.0, 50.0)
aug = RandomJPEG(jpeg_quality=jpegq, p=1.0)
aug.set_rng_device_and_dtype(device=torch.device(device), dtype=torch.float32)
example_input = torch.randn((3, 224, 224)).to(device)
res = aug(example_input)
```

btw, should this really be necessary? cc @shijianjian @edgarriba

2024-07-02 01:55 UTC, johnnv1 commented
hey, @ditwoo did you test the example I gave you? Has it fixed your issue?

2024-07-04 11:33 UTC, ditwoo commented
> hey, @ditwoo did you test the example I gave you? Has it fixed your issue?

Sorry, didn't have much time. I'll check this week and write to you with questions/updates.

2024-07-23 09:50 UTC, shijianjian commented
> even though it fixes your issue, this shouldn't be necessary...
> 
> 
> 
> The real issue is in the random generator https://github.com/kornia/kornia/blob/2387a2d165a977f1646332d6cbe6b915a4806e37/kornia/augmentation/random_generator/_2d/jpeg.py#L53 which is allocating and then casting it to the wrong device 
> 
> 
> 
> Can you test if in this case, where you want to use the nontensor as the bounds inputs, if you use the 
> 
> 
> 
> ```python
> 
> import torch
> 
> from kornia.augmentation import RandomJPEG
> 
> 
> 
> device = "cuda"
> 
> jpegq = (1.0, 50.0)
> 
> aug = RandomJPEG(jpeg_quality=jpegq, p=1.0)
> 
> aug.set_rng_device_and_dtype(device=torch.device(device), dtype=torch.float32)
> 
> example_input = torch.randn((3, 224, 224)).to(device)
> 
> res = aug(example_input)
> 
> ```
> 
> 
> 
> btw, should this really be necessary? cc @shijianjian @edgarriba 
> 
> 

It seems this solution is more elegant.

2024-12-07 19:13 UTC, closed without merging