new E decomposition without svd
kornia/kornia pull request #2920
Opened 2024-05-30 13:49 UTC by weitong8591

#### Changes
As SVD used in E decomposition is not stable for training, we would like to intergrate another methodthat recovers the two solutions for the baseline and the orientation from a given essential matrix using elementary matrix operations. This work was done by [Berthold K.P. Horn in 1990](https://people.csail.mit.edu/bkph/articles/Essential.pdf), and used in Generalized Differentiable RANSAC to build the pose erorr loss. 

Fixes # (issue)

#### Type of change

- [x] 📚  Documentation Update
- [x] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] 📝 This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

2024-06-04 12:08 UTC, weitong8591 commented
Hi! any suggestions about what to return if there is no solution?  It can't pass the tests. [link](https://github.com/weitong8591/kornia/blob/e8729cc77c2b9c3569c5d9d1b71fffbfd2be1d6a/kornia/geometry/epipolar/numeric.py#L47)

2024-06-04 21:06 UTC, johnnv1 commented
> Hi! any suggestions about what to return if there is no solution? It can't pass the tests. [link](https://github.com/weitong8591/kornia/blob/e8729cc77c2b9c3569c5d9d1b71fffbfd2be1d6a/kornia/geometry/epipolar/numeric.py#L47)

since we are randomly generating the input, we cannot determine when it'll be able to solve or not... i may say the best case here is to mark the test as xfail -- https://docs.pytest.org/en/stable/how-to/skipping.html#raises-parameter

2024-06-05 08:52 UTC, edgarriba requested changes

2024-06-05 08:52 UTC, edgarriba commented on kornia/geometry/epipolar/essential.py
> +      J. Opt. Soc. Am, 1990, 110.
```suggestion
      J. Opt. Soc. Am, 1990, 110.
      
```

2024-06-05 08:52 UTC, edgarriba commented on kornia/geometry/epipolar/essential.py
> +    r"""
```suggestion
    r"""Decompose the essential matrix to rotation and translation.
    
```

2024-06-05 08:58 UTC, weitong8591 commented on kornia/geometry/epipolar/essential.py
> +    B = E_mat.shape[0]
Sounds good, i will change it.

2024-06-05 09:00 UTC, weitong8591 commented
> > Hi! any suggestions about what to return if there is no solution? It can't pass the tests. [link](https://github.com/weitong8591/kornia/blob/e8729cc77c2b9c3569c5d9d1b71fffbfd2be1d6a/kornia/geometry/epipolar/numeric.py#L47)
> 
> since we are randomly generating the input, we cannot determine when it'll be able to solve or not... i may say the best case here is to mark the test as xfail -- https://docs.pytest.org/en/stable/how-to/skipping.html#raises-parameter

Thanks! let me try it

2024-06-05 09:37 UTC, weitong8591 commented on kornia/geometry/epipolar/essential.py
> +    B = E_mat.shape[0]
What about making it like, 
`elif len(E_mat.shape) != 3: 
        E_mat = E_mat.view(-1, 3, 3)`

2024-06-10 07:54 UTC, edgarriba approved these changes

2024-06-10 07:54 UTC, merged